jobs:
- job: StrykerMutationTest
  displayName: 'Run mutation tests with Stryker'
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      dotnet tool install -g dotnet-stryker
      dotnet stryker `
        --solution ../OmniStack.sln `
        --reporter html `
        --reporter progress `
        --output StrykerOutput `
        --threshold-high 80 `
        --threshold-low 60
    workingDirectory: 'WMB.Api.Tests'
    displayName: 'Run mutation tests with Stryker'

  - task: PublishMutationReport@2
    displayName: 'Publish Stryker Mutation Report'
    inputs:
      reportPattern: 'WMB.Api.Tests/StrykerOutput/**/mutation-report.html'
      reportDisplayName: 'Stryker Mutation Report'
